version: "3"
services:
    eventstore:
        image: "eventstore/eventstore"
        ports:
            - "2113:2113"
            - "1113:1113"
        environment:
            - EVENTSTORE_EXT_HTTP_PORT=2113
            - EVENTSTORE_EXT_TCP_PORT=1113
    couchbase:
        image: "osoykan/couchbase"
        ports:
            - "8091-8094:8091-8094"
            - "11210:11210"
        environment:
            - MEMORY_QUOTA=256
            - INDEX_MEMORY_QUOTA=256
            - FTS_MEMORY_QUOTA=256
            - SERVICES="kv,n1ql,index,fts"
            - USERNAME="Administrator"
            - PASSWORD="123456"