version: "3"
services:
    eventstore:
        image: "eventstore/eventstore"
        ports:
            - "2113:2113"
            - "1113:1113"
        environment:
            - EVENTSTORE_EXT_HTTP_PORT=2113
            - EVENTSTORE_EXT_TCP_PORT=1113
    couchbase:
        image: "couchbase"
        ports:
            - "8091-8094:8091-8094"
            - "11210:11210"