# Default values for eventstore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eventstore/eventstore
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  HTTPInterfacePort: 2113
  TCPInterfacePort: 1113

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
