replicaCount: 2

image:
  repository: productcontextes
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 5000
  nodePort: 31638
containerPort: 5000

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
